---
title: "Project Overview"
output: html_document
site: 
  distill::distill_website:
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Purpose:

This particular project is the first part of a bigger project that aims to use human mobility data that is used to study aspects of gentrification.We first wanted to investigate the various ways that gentrification could be defined, as there is no true and agreed upon definition for gentrification in the literature. The gold standard as of now is based on Freeman’s 2005 paper titled “Displacement or Succession? Residential Mobility in Gentrifying Neighborhoods”, which defines gentrification as having 5 major components. These components state that the area must be located in a central city at the start of the period of analysis, the median income of the area had to be less than the median for the greater area as a whole that is being studied, the proportion of housing built within the last two decades has to be more than that of the greater area being studied, the percentage of increase in educational attainment is more than the respective increase in the greater area being studied, and there must be an increase in housing prices throughout the duration of the period of analysis (Freeman, 2005). In a later paper conducted by Lei Ding, they chose tract level areas, and deemed gentrifiable to mean that a tract had a median household income lower than the citywide median income at the start of the period of analysis. They determined that a tract would be gentrifying for a given period of time if it was gentrifiable at the beginning of the period of analysis and saw an increase in median percent home value or gross rent above that of the greater area in question, and if there was an increase in college-educated people above the increase for the greater area (Ding, 2019). We took components from these papers, added some of our own variables based on the combed logic from the two papers. We then aimed to come up with varying definitions of our own in order to better understand what it means for an area to be gentrifying. 




## Project Methods:
The period of analysis for this project is 2010 to 2019. We chose to use the American Community Survey (ACS) rather than the United States Census, because the 2020 Census data was not released yet. Initially, we still wanted to use a full 10 years of difference like the census would have, however, there were inconsistencies with the data tables for 2009 that would be eliminated by starting with 2010, so we made the decision to start with 2010. We chose to use the year 2019 in ACS data rather than Census data, because the 2020 census data had not yet been released. Therefore, 2019 ACS data was more up to date than 2010 census data. We used American Community Survey (ACS) 5-year estimates rather than the 3-year and 1-year estimates, because the 3-year estimates had been discontinued, and the 1-year estimates were not offered for the Pittsburgh area at tract level. Additionally, we made the decision to use data from 2019, because it was not only the most recent data, but it was also data from before the Covid-19 pandemic. 

The data in this project were retrieved from two largest public data sources pertinent to our variables. These websites are the United States Census Bureau website and the National Historic Geographic Information Systems (NHGIS) website. NHGIS pulls data from the United States Census Bureau websites, and helps eliminate issues that corresponded with the Census Bureau’s updated versus previous website. After the data were obtained they were analyzed using the R Studio programming system. All of the possible variables used for any given definition included Educational Attainment, Home Value, Rent Cost, Income, and Vacancy. In addition to the 2019 data for our variables, we obtained 2010 data as well, which wwere only used for the purpose of defining a tract as gentrifiable. 2019 and 2010 American Community Survey data were retrieved from the Census for the Educational Attainment, Home Value, Income, and Vacancy variables. The 2019 and 2010 American Community Survey data were retrieved from NHGIS for the Rent variable. We chose to use NHGIS data for this variable because the particular table had more pertinent rent information, and less of a breakdown than the chart offered on the ACS Census website.

We chose to include additional tracts in our demarcation of the Pittsburgh Area beyond those that were technically classified as Pittsburgh census tracts. These were the tracts 9822, 4810, and 4803, and they were included because they were within the boundaries of Pittsburgh based on the other census tracts technically considered to be Pittsburgh tracts.

It is important to first note the specific definitions to the terms that we use in defining aspects of gentrification in this project. We sourced these definitions from Lei Ding and colleagues’ paper titled “Gentrification and Residential Mobility in Philadelphia.” Based on Ding’s paper, we say that if,the median household income for a tract  is below the city wide median at the beginning of the period of analysis, which in this case is 2010, then a census tract is Gentrifiable If a census tract is defined as gentrifiable at the beginning of our time period (2010) but it does not meet the criteria to be classified as gentrifying based on the gentrifying criteria for the corresponding definition, then it is classified as Non-gentrifying Within the definitions, we have several variables with cut offs that are combined in several different ways. 

Once the data were retrieved, we needed to first classify the tracts in the area of Pittsburgh as gentrifiable or non-gentrifiable. In order to determine if a tract is gentrifiable, we used income data from the beginning of the time period for which we are investigating. We first found the median of all of the tracts’ median household incomes, which we call the city wide median for household income. From there, we compared the median incomes for the individual tracts, and labeled them gentrifiable if the tract’s median household income was less than the citywide median for household income, and not gentrifiable if the median was at or above the city wide median for household income.

Since there is no one definition that is widely accepted for gentrification, we decided to take different definitions from literature sources and test variations of these definitions. The variables that we included were Median Household Income, Median Rent, Median Home Value, the proportion of vacant houses (Vacancy), and the proportion of tract population that has a bachelor’s degree or higher(Educational Attainment). Median Household Income was used both as a variable for the classification of gentrifiable, as well as for some of the definitions for gentrifying. The combinations of these variables into definitions can be found under the Gentrification Maps tab on this website. 

We used Education Attainment as a variable in our study, because both the Freeman and Ding papers used this variable, marking its importance, because educated individuals typically have a higher socioeconomic status than those who do not, and so it adds a level of depth that looking at income alone does not (Ding, 2019). For this variable, we used the “Educational Attainment” subject table from the Census website. From this table we were only interested in the ages 25 and older, and whether or not the individuals had attained a bachelor’s degree or higher. Analysis would be more effective if the number of individuals with a bachelor’s degree or higher was made into a proportion, so once the total number of individuals for each tract ages 25 and up were found, and once the total number of individuals with a bachelor’s degree or higher was found, we made a proportion of bachelors degree and higher individuals in each tract. This was the proportion used in determining if a tract was gentrifying or not. 

Household Income is also a variable that we investigated, because of one aspect of how many define gentrification, that there is an influx of affluent families that enter the area. For this variable, we used the “Household Income in the Past 12 Months” subject table from the Census website. From this table we only used the column for median household income. Percent increase was then calculated for the city (citywide median percent increase in household income), and then compared to the individual percent increases for Pittsburgh tracts to see if the increase for tracts was greater than the citywide median increase. 

Home Value was also an important variable, because it is a good measure for quality and value within the area at a given time (Ding 2019). For this variable, we used the “Financial Characteristics for Housing Units with a Mortgage” subject table from the Census website. From this table we only used the column for median home value for each tract. Citywide median percent increase in home value and percent increase in home value per tract were then calculated to see if the increase for tracts was greater than the citywide increase. 

Gross Rent was included for the same reasoning as Home Value. Rent prices will go up as the quality of the area improves (Ding 2019). For the variable Rent, we used the “Median Gross Rent (Dollars)” NHGIS table. From this table we only used the median gross rent estimates column. Citywide median percent increase in rent cost and percent increase in rent cost per tract were then calculated to see if the increase for tracts was greater than the citywide increase. 

Vacancy was used, because we wanted to examine the differences between the impact of vacancy decreasing in potentially gentrifying areas. For this variable, we used the “Occupancy Status” detailed table from the Census website. This table had counts for vacant and occupied properties, so we created a total, and then calculated the proportion of vacant residencies, because the decrease in proportion of vacant residencies would be easier to compare than counts. From there, we calculated the citywide median percent decrease for proportion of vacant residencies and compared that to the percent increase and decrease of proportion of vacant residencies for each tract over the given time period. 

The various definitions detailed under the Gentrification Maps tab give detailed breakdowns of what all of the possible definitions of gentrification mean. Here, you can also see the difference between all of the possible combinations of variables that readily go along with gentrification. 


## Why We Care:
Gentrification is defined as the socioeconomic upgrading of a previously, low income central city neighborhood, characterized by the influx of residents of a higher socioeconomic status relative to incumbent residents and rising home values and rents (Ding et al.). Gentrification as an isolated phenomenon is quite controversial, however, most have decided that the real problems lie in the displacement that has the potential to accompany gentrification. In 2005 Freeman found that gentrifying neighborhoods in the United States are significantly related to displacement of neighborhoods. This was done by comparing the mobility and displacement for similar neighborhoods where some of the neighborhoods had been gentrified while others had not (Freeman). Usually this displacement affects minority groups the most. The National Community Reinvestment Coalition (NCRC) released a report in 2019 based on data from 2000-20013 which stated that gentrification occurred in at least one tract for 24% of all urban areas in the United States (NCRC, 2019). Within these gentrified tracts, 187 of them showed displacement of black people. Among the 16 cities with the highest number of displaced black people, the average number of black people that were displaced in gentrified tracts was 593. Looking at the 10 cities with the highest number of displaced hispanic people, the average number of hispanic people that were displaced in gentrified tracts was 542 (NCRC, 2019). We need to care about what negative impacts follow gentrification, and in order to learn more about how to help those who are being impacted and displaced, we first need to understand more about the gentrification process, which is why this research is so important. 

### Citations
Freeman, Lance. “Displacement or Succession?: Residential Mobility in Gentrifying Neighborhoods.” Urban Affairs Review, vol. 40, no. 4, Mar. 2005, pp. 463–91. SAGE Journals, https://doi.org/10.1177/1078087404273341.

Ding, Lei, et al. “Gentrification and Residential Mobility in Philadelphia.” Regional Science and Urban Economics, vol. 61, Nov. 2016, pp. 38–51. ScienceDirect, https://doi.org/10.1016/j.regsciurbeco.2016.09.004.

Shifting Neighborhoods: Gentrification and Cultural Displacement in American Cities. NCRC. https://ncrc.org/gentrification/. Accessed 9 June 2021.





